-- @generated by x-publishing-contract generator v1.0.0. DO NOT EDIT.
-- Contract version: 1.0.0; source SHA-256: ae367786950c6284f1c6dbed6c03309bdd07be18a89ba3f62cf3712fa99f8ef6
return {
  _generated = {
    contractVersion = "1.0.0",
    generatorVersion = "1.0.0",
    notice = "DO NOT EDIT. Generated from the canonical X publishing contract.",
    sourceSha256 = "ae367786950c6284f1c6dbed6c03309bdd07be18a89ba3f62cf3712fa99f8ef6",
  },
  cases = {
    {
      expected = {
        operation = "post",
        status = "preview",
        text = "Contract fixture post",
        traceId = "trace-post",
      },
      id = "post_success",
      request = {
        idempotencyKey = "fixture-trace-post",
        operation = "post",
        text = "Contract fixture post",
        traceId = "trace-post",
      },
      requiredCapability = {
        operation = "post",
      },
    },
    {
      expected = {
        operation = "quote",
        providerFields = {
          quote_tweet_id = "1234567890123456789",
        },
        quoteMode = "native",
        quoteTargetPostId = "1234567890123456789",
        quoteTargetUrl = "https://x.com/Example_User/status/1234567890123456789",
        status = "preview",
        text = "Native Quote commentary",
        traceId = "trace-native-quote",
      },
      id = "native_quote_success",
      request = {
        idempotencyKey = "fixture-trace-native-quote",
        operation = "quote",
        quoteMode = "native",
        quoteTargetUrl = "https://twitter.com/Example_User/status/1234567890123456789?ref=fixture",
        text = "Native Quote commentary",
        traceId = "trace-native-quote",
      },
      requiredCapability = {
        operation = "quote",
        quoteMode = "native",
      },
    },
    {
      expected = {
        operation = "quote",
        providerFields = {},
        publishText = "Link Quote commentary\n\nhttps://x.com/example/status/2234567890123456789",
        quoteMode = "link",
        quoteTargetPostId = "2234567890123456789",
        quoteTargetUrl = "https://x.com/example/status/2234567890123456789",
        status = "preview",
        text = "Link Quote commentary",
        traceId = "trace-link-quote",
      },
      id = "link_quote_success",
      request = {
        idempotencyKey = "fixture-trace-link-quote",
        operation = "quote",
        quoteMode = "link",
        quoteTargetUrl = "https://X.com/example/status/2234567890123456789",
        text = "Link Quote commentary",
        traceId = "trace-link-quote",
      },
      requiredCapability = {
        operation = "quote",
        quoteMode = "link",
      },
    },
    {
      expected = {
        operation = "quote",
        providerFields = {},
        publishText = "Already linked https://x.com/example/status/3234567890123456789",
        quoteMode = "link",
        quoteTargetPostId = "3234567890123456789",
        quoteTargetUrl = "https://x.com/example/status/3234567890123456789",
        status = "preview",
        traceId = "trace-link-existing",
      },
      id = "link_quote_existing_target",
      request = {
        idempotencyKey = "fixture-trace-link-existing",
        operation = "quote",
        quoteMode = "link",
        quoteTargetUrl = "https://twitter.com/example/status/3234567890123456789?source=fixture",
        text = "Already linked https://x.com/example/status/3234567890123456789",
        traceId = "trace-link-existing",
      },
      requiredCapability = {
        operation = "quote",
        quoteMode = "link",
      },
    },
    {
      expected = {
        errorCode = "invalid_quote_target",
        operation = "quote",
        status = "blocked",
        traceId = "trace-invalid-target",
      },
      id = "invalid_quote_target",
      request = {
        idempotencyKey = "fixture-trace-invalid-target",
        operation = "quote",
        quoteMode = "native",
        quoteTargetUrl = "https://example.invalid/post/1",
        text = "Invalid target",
        traceId = "trace-invalid-target",
      },
    },
    {
      expected = {
        errorCode = "missing_required_field",
        operation = "quote",
        status = "blocked",
        traceId = "trace-missing-mode",
      },
      id = "missing_quote_mode",
      request = {
        idempotencyKey = "fixture-trace-missing-mode",
        operation = "quote",
        quoteTargetUrl = "https://x.com/example/status/4234567890123456789",
        text = "Missing mode",
        traceId = "trace-missing-mode",
      },
    },
    {
      expected = {
        errorCode = "missing_required_field",
        operation = "quote",
        status = "blocked",
        traceId = "trace-missing-target",
      },
      id = "missing_quote_target",
      request = {
        idempotencyKey = "fixture-trace-missing-target",
        operation = "quote",
        quoteMode = "link",
        text = "Missing target",
        traceId = "trace-missing-target",
      },
    },
    {
      consumer = "fkst-x-publisher",
      expected = {
        errorCode = "unsupported_capability",
        operation = "thread",
        status = "blocked",
        traceId = "trace-unsupported-operation",
      },
      id = "unsupported_operation",
      request = {
        idempotencyKey = "fixture-trace-unsupported-operation",
        operation = "thread",
        text = "Unsupported consumer thread",
        traceId = "trace-unsupported-operation",
      },
      requiredCapability = {
        operation = "thread",
      },
    },
    {
      adapterCapabilities = {
        operations = {
          "post",
          "quote",
        },
        quoteModes = {
          "link",
        },
      },
      expected = {
        errorCode = "unsupported_capability",
        operation = "quote",
        status = "blocked",
        traceId = "trace-unsupported-native",
      },
      id = "unsupported_native_capability",
      request = {
        idempotencyKey = "fixture-trace-unsupported-native",
        operation = "quote",
        quoteMode = "native",
        quoteTargetUrl = "https://x.com/example/status/5234567890123456789",
        text = "Native Quote without mode authority",
        traceId = "trace-unsupported-native",
      },
      requiredCapability = {
        operation = "quote",
        quoteMode = "native",
      },
    },
    {
      expected = {
        errorCode = "provider_failure",
        fallbackMode = nil,
        operation = "quote",
        quoteMode = "native",
        status = "blocked",
        traceId = "trace-native-provider-failure",
      },
      id = "native_provider_failure",
      providerResult = {
        errorCode = "provider_failure",
        status = "failed",
      },
      request = {
        idempotencyKey = "fixture-trace-native-provider-failure",
        operation = "quote",
        quoteMode = "native",
        quoteTargetUrl = "https://x.com/example/status/6234567890123456789",
        text = "Native provider failure",
        traceId = "trace-native-provider-failure",
      },
      requiredCapability = {
        operation = "quote",
        quoteMode = "native",
      },
    },
  },
  contractVersion = "1.0.0",
  schemaVersion = 1,
  sourceSha256 = "ae367786950c6284f1c6dbed6c03309bdd07be18a89ba3f62cf3712fa99f8ef6",
}
