-- @generated by x-publishing-contract generator v1.0.0. DO NOT EDIT.
-- Contract version: 1.0.0; source SHA-256: ae367786950c6284f1c6dbed6c03309bdd07be18a89ba3f62cf3712fa99f8ef6
return {
  consumer_capabilities = {
    ["auto-twitter"] = {
      operations = {
        "post",
        "thread",
        "reply",
        "quote",
      },
      quoteModes = {
        "native",
        "link",
      },
    },
    ["fkst-x-publisher"] = {
      operations = {
        "post",
        "quote",
      },
      quoteModes = {
        "native",
        "link",
      },
    },
  },
  error_codes = {
    "invalid_request",
    "missing_required_field",
    "unsupported_operation",
    "unsupported_quote_mode",
    "invalid_quote_target",
    "unsupported_capability",
    "provider_failure",
    "idempotency_conflict",
  },
  metadata = {
    contract_version = "1.0.0",
    generator_version = "1.0.0",
    notice = "DO NOT EDIT. Generated from the canonical X publishing contract.",
    source_path = "packages/specs/company/x-publishing.contract.v1.json",
    source_sha256 = "ae367786950c6284f1c6dbed6c03309bdd07be18a89ba3f62cf3712fa99f8ef6",
  },
  normalization = {
    linkQuote = {
      appendCanonicalUrlAtMostOnce = true,
      sendNativeProviderField = false,
    },
    nativeQuote = {
      fallbackMode = nil,
      providerPostIdField = "quoteTargetPostId",
    },
    quoteTarget = {
      allowedHosts = {
        "x.com",
        "twitter.com",
      },
      allowedSchemes = {
        "https",
      },
      canonicalHost = "x.com",
      dropQuery = true,
      rejectFragment = true,
      rejectPort = true,
      rejectUserInfo = true,
      statusPathPattern = "^/([A-Za-z0-9_]{1,15})/status/([0-9]+)$",
    },
  },
  operations = {
    {
      capability = "post",
      modes = {},
      name = "post",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
      },
    },
    {
      capability = "thread",
      modes = {},
      name = "thread",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
      },
    },
    {
      capability = "reply",
      modes = {},
      name = "reply",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
        "replyToPostId",
      },
    },
    {
      capability = "quote",
      modes = {
        "native",
        "link",
      },
      name = "quote",
      optionalFields = {
        "quoteTargetPostId",
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
        "quoteMode",
        "quoteTargetUrl",
      },
    },
  },
  operations_by_name = {
    post = {
      capability = "post",
      modes = {},
      name = "post",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
      },
    },
    quote = {
      capability = "quote",
      modes = {
        "native",
        "link",
      },
      name = "quote",
      optionalFields = {
        "quoteTargetPostId",
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
        "quoteMode",
        "quoteTargetUrl",
      },
    },
    reply = {
      capability = "reply",
      modes = {},
      name = "reply",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
        "replyToPostId",
      },
    },
    thread = {
      capability = "thread",
      modes = {},
      name = "thread",
      optionalFields = {
        "mediaRefs",
        "scheduledAt",
      },
      requiredFields = {
        "text",
        "idempotencyKey",
        "traceId",
      },
    },
  },
  receipt_statuses = {
    "preview",
    "blocked",
    "published",
  },
}
