#!/usr/bin/env python3
"""Validate the pinned, generated X publishing contract without network access."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import NoReturn


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = Path("contract-locks/x-publishing-contract.lock.json")
MANIFEST_PATH = Path("manifests/auto-twitter-marketing.json")
WORKSPACE_PATH = Path("fkst.workspace.toml")
EXTERNAL_LOCK_PATH = Path("fkst.lock")
RUN_SCRIPT_PATH = Path("scripts/run.sh")
ENV_EXAMPLE_PATH = Path(".fkst/env.example")
OFFICIAL_SOURCE_URL = "https://github.com/ChronoAIProject/fkst-hosted.git"
OFFICIAL_PACKAGE_PATH = "packages/github-proxy"
HOSTED_SHADOW_OFFICIAL_REF = "packages"
HOSTED_SHADOW_REF_CLASS = "mutable-shadow-only"
STABLE_HOSTED_RELEASE_STATUS = "blocked"
ACTIVE_ACCEPTANCE_PATH = Path("docs/hzz780-v0.3.0-rc.4-acceptance.md")
ACTIVE_PACKAGE_README_PATH = Path("packages/github-auto-twitter-marketing/README.md")
STABLE_HOSTED_BLOCKER_GUIDANCE = (
    "Do not start a Stable Hosted Session while stable_hosted_release=blocked."
)
FORBIDDEN_BLOCKED_STABLE_START_PHRASES = (
    "before starting stable",
    "stable session then takes over",
    "let stable sequentially take over",
    "由 stable 顺序接管",
    "再由 stable 顺序接管",
)
OFFICIAL_DESCRIPTOR_DOCS = (
    Path("README.md"),
    Path("docs/auto-twitter-marketing-workflow.md"),
    Path("docs/x-publishing-contract.md"),
    ACTIVE_ACCEPTANCE_PATH,
)
ACTIVE_BUSINESS_RELEASE_DOCS = (
    Path("README.md"),
    Path("docs/auto-twitter-marketing-workflow.md"),
    ACTIVE_ACCEPTANCE_PATH,
    ACTIVE_PACKAGE_README_PATH,
)
GENERATED_PATHS = (
    Path("libraries/contract/x_publishing_contract.lua"),
    Path("packages/x-publisher/tests/fixtures/x_publishing_conformance.lua"),
)
EXPECTED_GENERATED_PATHS = {path.as_posix() for path in GENERATED_PATHS}
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
SEMVER_PATTERN = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
)
SEMVER_CORE_IDENTIFIER = r"(?:0|[1-9][0-9]*)"
SEMVER_PRERELEASE_IDENTIFIER = (
    r"(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
)
PACKAGE_SEMVER = (
    rf"{SEMVER_CORE_IDENTIFIER}\."
    rf"{SEMVER_CORE_IDENTIFIER}\."
    rf"{SEMVER_CORE_IDENTIFIER}"
    rf"(?:-{SEMVER_PRERELEASE_IDENTIFIER}"
    rf"(?:\.{SEMVER_PRERELEASE_IDENTIFIER})*)?"
)
HEADER_PATTERN = re.compile(
    r"^-- @generated by x-publishing-contract generator v(?P<generator>[^.\s]+(?:\.[^.\s]+){2})\. DO NOT EDIT\.\n"
    r"-- Contract version: (?P<version>[^;]+); source SHA-256: (?P<digest>[0-9a-f]{64})$",
    re.MULTILINE,
)
PACKAGE_DESCRIPTOR_PATTERN = re.compile(
    r"^aelf-hzz780/fkst-packages-market-hzz@"
    rf"(?P<ref>v{PACKAGE_SEMVER}):"
    r"packages/(?P<package>x-publisher|github-auto-twitter-marketing|marketing-radar)$"
)
BUSINESS_RELEASE_DESCRIPTOR_PATTERN = re.compile(
    r"aelf-hzz780/fkst-packages-market-hzz@"
    rf"(?P<ref>v{PACKAGE_SEMVER}):"
    r"(?:manifests/auto-twitter-marketing\.json|"
    r"packages/(?:x-publisher|github-auto-twitter-marketing|marketing-radar))"
)
ACTIVE_RUNBOOK_PATTERN = re.compile(
    rf"hzz780-(?P<ref>v{PACKAGE_SEMVER})(?=-acceptance\.md)"
)
ACCEPTANCE_OFFICIAL_TREE_PATTERN = re.compile(
    r"(?:and tree|和 tree)\s+`?(?P<tree>sha256-[0-9A-Za-z]{1,128})`?",
    re.IGNORECASE,
)
EXPECTED_PACKAGES = {
    "x-publisher",
    "github-auto-twitter-marketing",
    "marketing-radar",
}


class ContractCheckError(Exception):
    def __init__(self, code: str, detail: str) -> None:
        super().__init__(detail)
        self.code = code
        self.detail = detail


def fail(code: str, detail: str) -> NoReturn:
    raise ContractCheckError(code, detail)


def load_lock() -> dict[str, object]:
    path = ROOT / LOCK_PATH
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("missing_lock", LOCK_PATH.as_posix())
    except (OSError, json.JSONDecodeError):
        fail("invalid_lock", LOCK_PATH.as_posix())
    if not isinstance(value, dict):
        fail("invalid_lock", LOCK_PATH.as_posix())
    return value


def validate_lock(lock: dict[str, object]) -> tuple[str, str, str, dict[str, str]]:
    version = lock.get("contractVersion")
    digest = lock.get("sourceSha256")
    generator = lock.get("generatorVersion")
    artifact_hashes = lock.get("artifactSha256")
    if (
        lock.get("generated") is not True
        or lock.get("schemaVersion") != 1
        or not isinstance(version, str)
        or SEMVER_PATTERN.fullmatch(version) is None
        or not isinstance(generator, str)
        or SEMVER_PATTERN.fullmatch(generator) is None
        or not isinstance(digest, str)
        or SHA256_PATTERN.fullmatch(digest) is None
        or not isinstance(artifact_hashes, dict)
    ):
        fail("invalid_lock", LOCK_PATH.as_posix())

    normalized_hashes: dict[str, str] = {}
    for key, value in artifact_hashes.items():
        if not isinstance(key, str) or not isinstance(value, str):
            fail("invalid_artifact_hashes", LOCK_PATH.as_posix())
        normalized_hashes[key] = value
    if set(normalized_hashes) != EXPECTED_GENERATED_PATHS or any(
        SHA256_PATTERN.fullmatch(value) is None for value in normalized_hashes.values()
    ):
        fail("invalid_artifact_hashes", LOCK_PATH.as_posix())
    return version, digest, generator, normalized_hashes


def discovered_generated_paths() -> set[str]:
    candidates = set()
    patterns = (
        "libraries/contract/x_publishing*.lua",
        "packages/x-publisher/tests/fixtures/x_publishing*.lua",
    )
    for pattern in patterns:
        for path in ROOT.glob(pattern):
            if path.is_file():
                candidates.add(path.relative_to(ROOT).as_posix())
    return candidates


def validate_package_descriptors(packages: object) -> str:
    if not isinstance(packages, list) or not all(
        isinstance(descriptor, str) for descriptor in packages
    ):
        fail("invalid_manifest_packages", MANIFEST_PATH.as_posix())
    refs: set[str] = set()
    names: set[str] = set()
    for descriptor in packages:
        match = PACKAGE_DESCRIPTOR_PATTERN.fullmatch(descriptor)
        if match is None:
            fail("mutable_or_invalid_package_ref", MANIFEST_PATH.as_posix())
        refs.add(match.group("ref"))
        names.add(match.group("package"))
    if names != EXPECTED_PACKAGES or len(refs) != 1:
        fail("inconsistent_manifest_packages", MANIFEST_PATH.as_posix())
    return next(iter(refs))


def validate_release_manifest() -> str:
    path = ROOT / MANIFEST_PATH
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("missing_manifest", MANIFEST_PATH.as_posix())
    except (OSError, json.JSONDecodeError):
        fail("invalid_manifest", MANIFEST_PATH.as_posix())
    if not isinstance(manifest, dict):
        fail("invalid_manifest", MANIFEST_PATH.as_posix())
    return validate_package_descriptors(manifest.get("packages"))


def validate_official_source_pin() -> str:
    path = ROOT / WORKSPACE_PATH
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        fail("missing_workspace", WORKSPACE_PATH.as_posix())
    except OSError:
        fail("invalid_workspace", WORKSPACE_PATH.as_posix())

    match = re.search(
        r'^\[\[external_sources\]\]\n'
        r'id = "fkst-official"\n'
        r'git = "https://github\.com/ChronoAIProject/fkst-hosted\.git"\n'
        r'rev = "(?P<rev>[0-9a-f]{40})"\n'
        r'packages = \["github-proxy"\]\n'
        r'libraries = \[\]\s*$',
        text,
        re.MULTILINE,
    )
    if match is None or text.count("[[external_sources]]") != 1:
        fail("mutable_or_invalid_official_source", WORKSPACE_PATH.as_posix())
    return match.group("rev")


def validate_official_lock(source_ref: str) -> str:
    try:
        text = (ROOT / EXTERNAL_LOCK_PATH).read_text(encoding="utf-8")
    except FileNotFoundError:
        fail("missing_external_lock", EXTERNAL_LOCK_PATH.as_posix())
    except OSError:
        fail("invalid_external_lock", EXTERNAL_LOCK_PATH.as_posix())
    match = re.fullmatch(
        r'\[\[external_source\]\]\n'
        r'id = "fkst-official"\n'
        r'git = "https://github\.com/ChronoAIProject/fkst-hosted\.git"\n'
        r'libraries = \[\]\n\n'
        r'\[external_source\.intent\]\n'
        r'rev = "(?P<intent>[0-9a-f]{40})"\n\n'
        r'\[external_source\.resolved\]\n'
        r'rev = "(?P<resolved>[0-9a-f]{40})"\n'
        r'tree_sha256 = "(?P<tree>sha256-[0-9a-f]{64})"\n?',
        text,
    )
    if match is None or match.group("intent") != source_ref \
            or match.group("resolved") != source_ref:
        fail("official_lock_drift", EXTERNAL_LOCK_PATH.as_posix())
    return match.group("tree")


def read_release_document(relative_path: Path) -> str:
    try:
        return (ROOT / relative_path).read_text(encoding="utf-8")
    except FileNotFoundError:
        fail("missing_release_document", relative_path.as_posix())
    except OSError:
        fail("unreadable_release_document", relative_path.as_posix())


def validate_active_business_release_docs(package_ref: str) -> None:
    for relative_path in ACTIVE_BUSINESS_RELEASE_DOCS:
        text = read_release_document(relative_path)
        refs = {
            match.group("ref")
            for pattern in (
                BUSINESS_RELEASE_DESCRIPTOR_PATTERN,
                ACTIVE_RUNBOOK_PATTERN,
            )
            for match in pattern.finditer(text)
        }
        if not refs:
            fail("missing_business_release_ref", relative_path.as_posix())
        if refs != {package_ref}:
            fail(
                "business_release_ref_drift",
                f"{relative_path.as_posix()} expected={package_ref} "
                f"observed={','.join(sorted(refs))}",
            )


def validate_acceptance_official_tree(official_tree: str) -> None:
    text = read_release_document(ACTIVE_ACCEPTANCE_PATH)
    observed = {
        match.group("tree")
        for match in ACCEPTANCE_OFFICIAL_TREE_PATTERN.finditer(text)
    }
    if observed != {official_tree}:
        fail(
            "official_tree_doc_drift",
            f"{ACTIVE_ACCEPTANCE_PATH.as_posix()} expected={official_tree} "
            f"observed={','.join(sorted(observed)) or 'missing'}",
        )


def classify_hosted_official_ref(hosted_ref: str) -> str:
    if re.fullmatch(r"[0-9A-Fa-f]{40}", hosted_ref) is not None:
        fail(
            "hosted_raw_sha_unsupported",
            "the current Hosted clone path accepts branch/tag refs but cannot start "
            "a package workspace from a raw commit SHA",
        )
    if hosted_ref == HOSTED_SHADOW_OFFICIAL_REF:
        return HOSTED_SHADOW_REF_CLASS
    fail("unsupported_hosted_official_ref", hosted_ref)


def validate_official_release_descriptors(source_ref: str) -> str:
    expected = (
        f"ChronoAIProject/fkst-hosted@{HOSTED_SHADOW_OFFICIAL_REF}:"
        f"{OFFICIAL_PACKAGE_PATH}"
    )
    descriptor_pattern = re.compile(
        r"ChronoAIProject/fkst-hosted@([^:`\s]+):packages/github-proxy"
    )
    observed_classes: set[str] = set()
    for relative_path in OFFICIAL_DESCRIPTOR_DOCS:
        text = read_release_document(relative_path)
        refs = descriptor_pattern.findall(text)
        if not refs:
            fail("official_descriptor_drift", relative_path.as_posix())
        for hosted_ref in refs:
            observed_classes.add(classify_hosted_official_ref(hosted_ref))
        if expected not in text:
            fail("official_descriptor_drift", relative_path.as_posix())
        if STABLE_HOSTED_BLOCKER_GUIDANCE not in text:
            fail("missing_stable_hosted_blocker_guidance", relative_path.as_posix())
        lowered = text.lower()
        if STABLE_HOSTED_RELEASE_STATUS == "blocked" and any(
            phrase in lowered for phrase in FORBIDDEN_BLOCKED_STABLE_START_PHRASES
        ):
            fail("stable_hosted_blocker_contradiction", relative_path.as_posix())

    acceptance = (ROOT / OFFICIAL_DESCRIPTOR_DOCS[-1]).read_text(encoding="utf-8")
    if source_ref not in acceptance:
        fail("missing_official_shadow_sha_guard", OFFICIAL_DESCRIPTOR_DOCS[-1].as_posix())

    try:
        run_script = (ROOT / RUN_SCRIPT_PATH).read_text(encoding="utf-8")
    except FileNotFoundError:
        fail("missing_run_script", RUN_SCRIPT_PATH.as_posix())
    except OSError:
        fail("unreadable_run_script", RUN_SCRIPT_PATH.as_posix())
    matches = re.findall(
        r'^DEFAULT_OFFICIAL_SOURCE_REF="([0-9a-f]{40})"$',
        run_script,
        re.MULTILINE,
    )
    url_matches = re.findall(
        r'^DEFAULT_OFFICIAL_SOURCE_URL="([^"]+)"$', run_script, re.MULTILINE
    )
    if matches != [source_ref] or url_matches != [OFFICIAL_SOURCE_URL]:
        fail("official_runtime_pin_drift", RUN_SCRIPT_PATH.as_posix())

    try:
        env_example = (ROOT / ENV_EXAMPLE_PATH).read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        fail("invalid_env_example", ENV_EXAMPLE_PATH.as_posix())
    env_refs = re.findall(
        r'^# FKST_OFFICIAL_PACKAGE_SOURCE_REF=([0-9a-f]{40})$',
        env_example,
        re.MULTILINE,
    )
    if env_refs != [source_ref]:
        fail("official_env_pin_drift", ENV_EXAMPLE_PATH.as_posix())
    if observed_classes != {HOSTED_SHADOW_REF_CLASS}:
        fail("official_descriptor_drift", "hosted-ref-class")
    return HOSTED_SHADOW_REF_CLASS


def validate_artifact(
    relative_path: Path,
    expected_version: str,
    expected_digest: str,
    expected_generator: str,
    expected_hash: str,
) -> None:
    path = ROOT / relative_path
    try:
        content = path.read_bytes()
    except FileNotFoundError:
        fail("missing_artifact", relative_path.as_posix())
    except OSError:
        fail("unreadable_artifact", relative_path.as_posix())

    actual_hash = hashlib.sha256(content).hexdigest()
    if actual_hash != expected_hash:
        fail("artifact_drift", relative_path.as_posix())
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        fail("invalid_artifact", relative_path.as_posix())
    header = HEADER_PATTERN.search(text)
    if header is None:
        fail("missing_generated_metadata", relative_path.as_posix())
    if (
        header.group("version") != expected_version
        or header.group("digest") != expected_digest
        or header.group("generator") != expected_generator
    ):
        fail("metadata_drift", relative_path.as_posix())


def main() -> int:
    lock = load_lock()
    version, digest, generator, artifact_hashes = validate_lock(lock)
    discovered = discovered_generated_paths()
    if discovered != EXPECTED_GENERATED_PATHS:
        fail("generated_allowlist_drift", "generated-artifact-set")
    for relative_path in GENERATED_PATHS:
        validate_artifact(
            relative_path,
            version,
            digest,
            generator,
            artifact_hashes[relative_path.as_posix()],
        )
    package_ref = validate_release_manifest()
    official_ref = validate_official_source_pin()
    official_tree = validate_official_lock(official_ref)
    validate_active_business_release_docs(package_ref)
    validate_acceptance_official_tree(official_tree)
    hosted_ref_class = validate_official_release_descriptors(official_ref)
    print(
        "X_PUBLISHING_CONTRACT_CHECK_OK "
        f"version={version} source_sha256={digest} artifacts={len(GENERATED_PATHS)} "
        f"package_ref={package_ref} official_ref={official_ref} official_tree={official_tree} "
        f"hosted_official_ref={HOSTED_SHADOW_OFFICIAL_REF} "
        f"hosted_ref_class={hosted_ref_class} "
        f"stable_hosted_release={STABLE_HOSTED_RELEASE_STATUS}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ContractCheckError as error:
        print(
            f"X_PUBLISHING_CONTRACT_CHECK_FAILED code={error.code} detail={error.detail}",
            file=sys.stderr,
        )
        raise SystemExit(1)
