#!/usr/bin/env python3
"""Validate the pinned, generated X publishing contract without network access."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import NoReturn


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = Path("contract-locks/x-publishing-contract.lock.json")
GENERATED_PATHS = (
    Path("libraries/contract/x_publishing_contract.lua"),
    Path("packages/x-publisher/tests/fixtures/x_publishing_conformance.lua"),
)
EXPECTED_GENERATED_PATHS = {path.as_posix() for path in GENERATED_PATHS}
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
SEMVER_PATTERN = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
)
HEADER_PATTERN = re.compile(
    r"^-- @generated by x-publishing-contract generator v(?P<generator>[^.\s]+(?:\.[^.\s]+){2})\. DO NOT EDIT\.\n"
    r"-- Contract version: (?P<version>[^;]+); source SHA-256: (?P<digest>[0-9a-f]{64})$",
    re.MULTILINE,
)


class ContractCheckError(Exception):
    def __init__(self, code: str, detail: str) -> None:
        super().__init__(detail)
        self.code = code
        self.detail = detail


def fail(code: str, detail: str) -> NoReturn:
    raise ContractCheckError(code, detail)


def load_lock() -> dict[str, object]:
    path = ROOT / LOCK_PATH
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("missing_lock", LOCK_PATH.as_posix())
    except (OSError, json.JSONDecodeError):
        fail("invalid_lock", LOCK_PATH.as_posix())
    if not isinstance(value, dict):
        fail("invalid_lock", LOCK_PATH.as_posix())
    return value


def validate_lock(lock: dict[str, object]) -> tuple[str, str, str, dict[str, str]]:
    version = lock.get("contractVersion")
    digest = lock.get("sourceSha256")
    generator = lock.get("generatorVersion")
    artifact_hashes = lock.get("artifactSha256")
    if (
        lock.get("generated") is not True
        or lock.get("schemaVersion") != 1
        or not isinstance(version, str)
        or SEMVER_PATTERN.fullmatch(version) is None
        or not isinstance(generator, str)
        or SEMVER_PATTERN.fullmatch(generator) is None
        or not isinstance(digest, str)
        or SHA256_PATTERN.fullmatch(digest) is None
        or not isinstance(artifact_hashes, dict)
    ):
        fail("invalid_lock", LOCK_PATH.as_posix())

    normalized_hashes: dict[str, str] = {}
    for key, value in artifact_hashes.items():
        if not isinstance(key, str) or not isinstance(value, str):
            fail("invalid_artifact_hashes", LOCK_PATH.as_posix())
        normalized_hashes[key] = value
    if set(normalized_hashes) != EXPECTED_GENERATED_PATHS or any(
        SHA256_PATTERN.fullmatch(value) is None for value in normalized_hashes.values()
    ):
        fail("invalid_artifact_hashes", LOCK_PATH.as_posix())
    return version, digest, generator, normalized_hashes


def discovered_generated_paths() -> set[str]:
    candidates = set()
    patterns = (
        "libraries/contract/x_publishing*.lua",
        "packages/x-publisher/tests/fixtures/x_publishing*.lua",
    )
    for pattern in patterns:
        for path in ROOT.glob(pattern):
            if path.is_file():
                candidates.add(path.relative_to(ROOT).as_posix())
    return candidates


def validate_artifact(
    relative_path: Path,
    expected_version: str,
    expected_digest: str,
    expected_generator: str,
    expected_hash: str,
) -> None:
    path = ROOT / relative_path
    try:
        content = path.read_bytes()
    except FileNotFoundError:
        fail("missing_artifact", relative_path.as_posix())
    except OSError:
        fail("unreadable_artifact", relative_path.as_posix())

    actual_hash = hashlib.sha256(content).hexdigest()
    if actual_hash != expected_hash:
        fail("artifact_drift", relative_path.as_posix())
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        fail("invalid_artifact", relative_path.as_posix())
    header = HEADER_PATTERN.search(text)
    if header is None:
        fail("missing_generated_metadata", relative_path.as_posix())
    if (
        header.group("version") != expected_version
        or header.group("digest") != expected_digest
        or header.group("generator") != expected_generator
    ):
        fail("metadata_drift", relative_path.as_posix())


def main() -> int:
    lock = load_lock()
    version, digest, generator, artifact_hashes = validate_lock(lock)
    discovered = discovered_generated_paths()
    if discovered != EXPECTED_GENERATED_PATHS:
        fail("generated_allowlist_drift", "generated-artifact-set")
    for relative_path in GENERATED_PATHS:
        validate_artifact(
            relative_path,
            version,
            digest,
            generator,
            artifact_hashes[relative_path.as_posix()],
        )
    print(
        "X_PUBLISHING_CONTRACT_CHECK_OK "
        f"version={version} source_sha256={digest} artifacts={len(GENERATED_PATHS)}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ContractCheckError as error:
        print(
            f"X_PUBLISHING_CONTRACT_CHECK_FAILED code={error.code} detail={error.detail}",
            file=sys.stderr,
        )
        raise SystemExit(1)
